In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


## intro to tensors


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim


0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim


1

In [9]:
 vector.shape


torch.Size([2])

In [12]:
matrix = torch.tensor([[7,8],[9,10]])
matrix


tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim


2

In [16]:
matrix[1]

tensor([ 9, 10])

In [17]:
matrix.shape

torch.Size([2, 2])

In [26]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR.ndim
TENSOR.shape

torch.Size([3, 3, 3])

In [34]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3202, 0.0713, 0.2877, 0.1502],
        [0.5202, 0.1596, 0.4958, 0.1608],
        [0.7084, 0.0835, 0.2173, 0.9214]])

In [37]:
 random_image_size_tensor = torch.rand(size=(3,224,224))
 random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [40]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
ones.dtype

torch.float32

In [50]:
one_to_ten = torch.arange(1,11,1)

In [53]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = torch.float16,
                               device= None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)