<h1>OR Gate</h1>

In [3]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoidDerivative(x):
    return x*(1-x)


class NeuralNetwork:
    def __init__(self,N):
        self.inputSize=2
        self.hiddenSize=N
        self.outputSize=1
        self.learningRate=1
        self.W1=np.random.rand(self.inputSize,self.hiddenSize)
        self.W2=np.random.rand(self.hiddenSize,self.outputSize)

    def forward(self,X):
        self.B1=sigmoid(np.dot(X,self.W1))
        output=sigmoid(np.dot(self.B1,self.W2))
        return output

    def backward(self,X,Y,Output):
        outputError = (Y-Output)
        outputDelta = outputError*sigmoidDerivative(Output)
        self.W2 +=np.dot(self.B1.T,outputDelta)*self.learningRate

        hiddenError = np.dot(outputDelta,self.W2.T)
        hiddenDelta = hiddenError*sigmoidDerivative(self.B1)
        self.W1 +=np.dot(X.T,hiddenDelta)*self.learningRate

    def train(self,X,Y):
        error=1
        iteration=0
        while error>0.01:
            output = self.forward(X)
            self.backward(X,Y,output)
            error = np.mean(np.square(Y-output))
            iteration+=1
            print(f"Iteration: {iteration}, Error: {error}, Output:\n{output}")

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [1]])
nn=NeuralNetwork(10)
nn.train(X,Y)

print(f"\nOutput After Training:")
for i in range(len(X)):
    print(f"Input:{X[i]} Output: {nn.forward(X[i])}")

Iteration: 1, Error: 0.22763836565661763, Output:
[[0.95352124]
 [0.98011574]
 [0.97186734]
 [0.98719821]]
Iteration: 2, Error: 0.2254910958014039, Output:
[[0.94880797]
 [0.97735682]
 [0.96844011]
 [0.98519868]]
Iteration: 3, Error: 0.22296800684469315, Output:
[[0.94319519]
 [0.97394746]
 [0.96427391]
 [0.98268615]]
Iteration: 4, Error: 0.21998356603811725, Output:
[[0.93644263]
 [0.96967666]
 [0.95914773]
 [0.97948067]]
Iteration: 5, Error: 0.21643500697226528, Output:
[[0.92823588]
 [0.96425139]
 [0.95276229]
 [0.97532595]]
Iteration: 6, Error: 0.21220624915228353, Output:
[[0.91816864]
 [0.95726553]
 [0.9447148 ]
 [0.96985598]]
Iteration: 7, Error: 0.2071838122661917, Output:
[[0.9057333 ]
 [0.94816584]
 [0.93447569]
 [0.96255377]]
Iteration: 8, Error: 0.20129840632636714, Output:
[[0.89034386]
 [0.9362345 ]
 [0.92138907]
 [0.95271661]]
Iteration: 9, Error: 0.1946120686837272, Output:
[[0.8714449 ]
 [0.92064545]
 [0.90475246]
 [0.93947868]]
Iteration: 10, Error: 0.1874588323283512

<h1>AND Gate</h1>

In [7]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoidDerivative(x):
    return x*(1-x)


class NeuralNetwork:
    def __init__(self,N):
        self.inputSize=2
        self.hiddenSize=N
        self.outputSize=1
        self.learningRate=1
        self.W1=np.random.rand(self.inputSize,self.hiddenSize)
        self.W2=np.random.rand(self.hiddenSize,self.outputSize)

    def forward(self,X):
        self.B1=sigmoid(np.dot(X,self.W1))
        output=sigmoid(np.dot(self.B1,self.W2))
        return output

    def backward(self,X,Y,Output):
        outputError = (Y-Output)
        outputDelta = outputError*sigmoidDerivative(Output)
        self.W2 +=np.dot(self.B1.T,outputDelta)*self.learningRate

        hiddenError = np.dot(outputDelta,self.W2.T)
        hiddenDelta = hiddenError*sigmoidDerivative(self.B1)
        self.W1 +=np.dot(X.T,hiddenDelta)*self.learningRate

    def train(self,X,Y):
        error=1
        iteration=0
        while error>0.07:
            output = self.forward(X)
            self.backward(X,Y,output)
            error = np.mean(np.square(Y-output))
            iteration+=1
            print(f"Iteration: {iteration}, Error: {error}, Output:\n{output}")

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [0], [0], [1]])
nn=NeuralNetwork(3)
nn.train(X,Y)

print(f"\nOutput After Training:")
for i in range(len(X)):
    print(f"Input:{X[i]} Output: {nn.forward(X[i])}")

Iteration: 1, Error: 0.41021926563343764, Output:
[[0.6914653 ]
 [0.74661725]
 [0.74714418]
 [0.78299524]]
Iteration: 2, Error: 0.3328930371894206, Output:
[[0.613839  ]
 [0.65520752]
 [0.64978791]
 [0.67867057]]
Iteration: 3, Error: 0.2729224849337243, Output:
[[0.53671285]
 [0.55982601]
 [0.54793076]
 [0.56411472]]
Iteration: 4, Error: 0.23950501150724784, Output:
[[0.47607576]
 [0.48319055]
 [0.46668711]
 [0.47075341]]
Iteration: 5, Error: 0.2237361012834549, Output:
[[0.43454146]
 [0.43064116]
 [0.41161013]
 [0.40734207]]
Iteration: 6, Error: 0.21620228797901608, Output:
[[0.4065286 ]
 [0.39553016]
 [0.3752196 ]
 [0.36572104]]
Iteration: 7, Error: 0.2123025728647464, Output:
[[0.38697871]
 [0.37137355]
 [0.3504272 ]
 [0.33762531]]
Iteration: 8, Error: 0.2100965335404248, Output:
[[0.37277735]
 [0.35412805]
 [0.33288027]
 [0.31793898]]
Iteration: 9, Error: 0.20873701893837104, Output:
[[0.36209583]
 [0.34141825]
 [0.32005056]
 [0.30369841]]
Iteration: 10, Error: 0.20782630461086624,