In [40]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoidDerivative(x):
    return x*(1-x)


class NeuralNetwork:
    def __init__(self,N):
        self.inputSize=2
        self.hiddenSize=N
        self.outputSize=1
        self.learningRate=1
        self.W1=np.random.rand(self.inputSize,self.hiddenSize)
        self.W2=np.random.rand(self.hiddenSize,self.outputSize)

    def forward(self,X):
        self.B1=sigmoid(np.dot(X,self.W1))
        output=sigmoid(np.dot(self.B1,self.W2))
        return output

    def backward(self,X,Y,Output):
        outputError = (Y-Output)
        outputDelta = outputError*sigmoidDerivative(Output)
        self.W2 +=np.dot(self.B1.T,outputDelta)*self.learningRate

        hiddenError = np.dot(outputDelta,self.W2.T)
        hiddenDelta = hiddenError*sigmoidDerivative(self.B1)
        self.W1 +=np.dot(X.T,hiddenDelta)*self.learningRate
    
    def train(self,X,Y):
        error=1
        iteration=0
        while error>0.01:
            output = self.forward(X)
            self.backward(X,Y,output)
            error = np.mean(np.square(Y-output))
            iteration+=1
            print(f"Iteration: {iteration}, Error: {error}, Output:\n{output}")

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])
nn=NeuralNetwork(3)
nn.train(X,Y)

print(f"\nOutput After Training:")
for i in range(len(X)):
    print(f"Input:{X[i]} Output: {nn.forward(X[i])}")




    





        





Iteration: 1, Error: 0.49950210118700333, Output:
[[0.99906689]
 [0.99976148]
 [0.99978965]
 [0.99993682]]
Iteration: 2, Error: 0.49949819232177384, Output:
[[0.99905974]
 [0.99975929]
 [0.99978769]
 [0.99993615]]
Iteration: 3, Error: 0.4994942212587369, Output:
[[0.99905248]
 [0.99975705]
 [0.99978569]
 [0.99993546]]
Iteration: 4, Error: 0.49949018649896626, Output:
[[0.99904511]
 [0.99975477]
 [0.99978366]
 [0.99993476]]
Iteration: 5, Error: 0.49948608649495346, Output:
[[0.99903761]
 [0.99975246]
 [0.9997816 ]
 [0.99993404]]
Iteration: 6, Error: 0.4994819196486227, Output:
[[0.99903   ]
 [0.9997501 ]
 [0.9997795 ]
 [0.99993331]]
Iteration: 7, Error: 0.499477684309249, Output:
[[0.99902226]
 [0.99974771]
 [0.99977736]
 [0.99993257]]
Iteration: 8, Error: 0.4994733787712701, Output:
[[0.9990144 ]
 [0.99974526]
 [0.99977518]
 [0.99993181]]
Iteration: 9, Error: 0.4994690012719919, Output:
[[0.99900641]
 [0.99974278]
 [0.99977296]
 [0.99993104]]
Iteration: 10, Error: 0.4994645499891744, O